# Generated by Django 3.1.7 on 2021-03-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Elemento', models.CharField(max_length=200)),
                ('Descripción_1', models.CharField(max_length=200)),
                ('Causa_1', models.TextField()),
                ('Efectos_1', models.TextField()),
                ('Descripción_2', models.CharField(max_length=200)),
                ('Causa_2', models.TextField()),
                ('Efectos_2', models.TextField()),
                ('Descripción_3', models.CharField(max_length=200)),
                ('Causa_3', models.TextField()),
                ('Efectos_3', models.TextField()),
                ('Descripción_4', models.CharField(max_length=200)),
                ('Causa_4', models.TextField()),
                ('Efectos_4', models.TextField()),
                ('Descripción_5', models.CharField(max_length=200)),
                ('Causa_5', models.TextField()),
                ('Efectos_5', models.TextField()),
                ('Descripción_6', models.CharField(max_length=200)),
                ('Causa_6', models.TextField()),
                ('Efectos_6', models.TextField()),
                ('Descripción_7', models.CharField(max_length=200)),
                ('Causa_7', models.TextField()),
                ('Efectos_7', models.TextField()),
                ('Descripción_8', models.CharField(max_length=200)),
                ('Causa_8', models.TextField()),
                ('Efectos_8', models.TextField()),
                ('Descripción_9', models.CharField(max_length=200)),
                ('Causa_9', models.TextField()),
                ('Efectos_9', models.TextField()),
                ('Descripción_10', models.CharField(max_length=200)),
                ('Causa_10', models.TextField()),
                ('Efectos_10', models.TextField()),
                ('Descripción_11', models.CharField(max_length=200)),
                ('Causa_11', models.TextField()),
                ('Efectos_11', models.TextField()),
                ('Descripción_12', models.CharField(max_length=200)),
                ('Causa_12', models.TextField()),
                ('Efectos_12', models.TextField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
