# Generated by Django 3.1.7 on 2021-03-24 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TES', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Datos_Creados',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='Datos_Publicados',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
